### ISSUE TITLE
Config to make Scrapmire sound not global

### ISSUE THREAD

**Issue by brandyyn** [lincolnrelias/Scrapmire#1]
some of my friends hate that its a global sound, i dont mind personally but it would be cool for it to be a config option since i love scrapmire

**Comment by aaronhowser1** [comment]
I am begging you

**Comment by brandyyn** [comment]
add more voice lines
like giggity giggity goo

**Comment by brandyyn** [comment]
@lincolnrelias

**Comment by lincolnrelias** [comment]
it wasn't intended to play globally, pretty sure it's fixed now, lmk if still happening

**Comment by brandyyn** [comment]
if u dont add more voice lines i will personally fuck you

**Comment by lincolnrelias** [comment]
I'm trying bro relax 😭

**Comment by brandyyn** [comment]
> I'm trying bro relax 😭

hahahah love u bro

**Comment by aaronhowser1** [comment]
Make a new issue for it smfh brandyn i will actually stab you

**Comment by brandyyn** [comment]
> Make a new issue for it smfh brandyn i will actually stab you

I will fuck your fat ass

**Comment by aaronhowser1** [comment]
Why do you choose to be the way that you are

**Comment by brandyyn** [comment]
> Why do you choose to be the way that you are

If I made a new issue it would DOUBLE the amount of issues he has ever had

**Comment by aaronhowser1** [comment]
Theoretically, maybe, possibly

what if it constantly went giggity while held, like the toy robot

**Comment by brandyyn** [comment]
> Theoretically, maybe, possibly
> 
> what if it constantly went giggity while held, like the toy robot

THATS A GOOD IDEA ESPECIALLY SINCE ITS WORTH SOOO MUCH

**Comment by lincolnrelias** [comment]
added a bunch of voicelines as sfx, I'm testing the suggestions of playing sounds while you carry it but that'll take a little more time

**Comment by aaronhowser1** [comment]
Dev confirmed to be goated with the sauce bustin it down sexual style

**Comment by brandyyn** [comment]
> added a bunch of voicelines as sfx, I'm testing the suggestions of playing sounds while you carry it but that'll take a little more time

MY GOAT

**Comment by brandyyn** [comment]
It is still a global sound :/

**Comment by lincolnrelias** [comment]
> It is still a global sound :/

is it only on pickup or on drop too?

**Comment by brandyyn** [comment]
> > It is still a global sound :/
> 
> is it only on pickup or on drop too?

i think both?

**Comment by lincolnrelias** [comment]
> It is still a global sound :/

all right now I'm pretty sure it's fixed, even tested it with a friend so should be ok, but if it has any other problems lmk
